config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"
  post '/check' => "home#check"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def check
    # puts params
    # 今は何を入力しても下の配列が入れられる状態
    # 入れた文字列を読み込む形式に変更
    # リクエストを動的にする
    # ハッシュと配列の意味と取り出し方を考える
    # ["H1 H13 H12 H11 H10"]の部分だけ変える

    # request_body = {cards: ["H1 H13 H12 H11 H10"]}
    request_body = {cards: [params[:cards]]}

    request_header = {"Content-Type" => "application/json"}

    url = 'http://p0kerhands.herokuapp.com/api/v1/cards/check'
    response = CallApi.post(url, request_body, request_header)

    # data = {"result"=>[{"card"=>"C10 C5 C4 C11 C7", "hand"=>"フラッシュ", "best"=>true}]}
    # @yaku = response[result: "hand"]
    if response["result"]
      @yaku = response["result"][0]["hand"]
    else
      @yaku = response["error"][0]["msg"]
    end

    # yaku_params
    # @yaku = response
  end

  def yaku_params
    params["cards"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/check.html.erb
<!DOCTYPE html>

<html>

<head>
</head>

<body>
<%= render 'template/pokertemp' %>
<div class="main.input">
  <%= render 'template/pokertemp3' %>
    <div class="output.result">
      <%= @yaku%>
    </div>
</div>
<%= render 'template/pokertemp2' %>
</body>

</html>

app/views/home/top.html.erb
<!DOCTYPE html>

<html>

<head>
</head>

<body>
  <%= render 'template/pokertemp' %>
  <div class="main.input">
    <%= render 'template/pokertemp3' %>
  </div>
  <%= render 'template/pokertemp2' %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/template/_poker_bottom.html.erb
<div class="footer">
  <div class="foot.buttom">
    <p>Created by shuuemura for the purpose of learning atone/AFTEE</p>
  </div>
</div>

app/views/template/_poker_form.html.erb
<%= form_tag(check_path, method: :post) do %>
  <div class="input.form">
    <%= text_field_tag "cards", "H1 H13 H12 H11 H10" %>
  </div>
  <div class="main.submit">
    <%= submit_tag "check" %>
  </div>
<% end %>

app/views/template/_poker_top.html.erb
<div class="main.top">
  <h1>Check your poker hand</h1>
</div>

app/views/template/_pokertemp.html.erb
<div class="main.top">
  <h1>Check your poker hand</h1>
</div>

app/views/template/_pokertemp2.html.erb
<div class="footer">
  <div class="foot.buttom">
    <p>Created by shuuemura for the purpose of learning atone/AFTEE</p>
  </div>
</div>

app/views/template/_pokertemp3.html.erb
<%= form_tag(check_path, method: :post) do %>
  <div class="input.form">
    <%= text_field_tag "cards", "H1 H13 H12 H11 H10" %>
  </div>
  <div class="main.submit">
    <%= submit_tag "check" %>
  </div>
<% end %>